### ISSUE TITLE
Cannot read property 'name' of undefined (again)

### ISSUE THREAD

**Issue by HansHammel** [strongloop/loopback-explorer#71]
I just updated to the latest version and got 

<pre><code>
TypeError: Cannot read property 'name' of undefined
    at generateModelDefinition (C:\bla\node_modules\loopback-explorer\lib\model-helper.js:24:19)
    at Object.generateModelDefinition (C:\bla\node_modules\loopback-explorer\lib\model-helper.js:110:7)
    at Object.module.exports.generateAPIDoc (C:\bla\node_modules\loopback-explorer\lib\class-helper.js:34:27)
    at C:\bla\node_modules\loopback-explorer\lib\swagger.js:63:50
    at Array.forEach (native)
    at Swagger (C:\bla\node_modules\loopback-explorer\lib\swagger.js:62:11)
    at explorer (C:\bla\node_modules\loopback-explorer\index.js:31:3)
    at Object.mountLoopBackExplorer [as func] (C:\bla\server\boot\explorer.js:14:21)
    at C:\bla\node_modules\loopback-boot\lib\executor.js:225:9
    at iterate (C:\bla\node_modules\loopback-boot\node_modules\async\lib\async.js:149:13) </code> </pre>

related to <a href="https://github.com/strongloop/loopback-explorer/pull/49">#49</a>/<a href="https://github.com/strongloop/loopback-explorer/pull/50">#50</a>
Still don't know why, but hot-fixed it (lib/model-helper.js @ line 108) with

<pre><code>
   for (var i = 0, n = referencedModels.length; i < n; i++) {
      <strong>if(referencedModels[i].definition)</strong>
      generateModelDefinition(referencedModels[i], out);
    }
</code></pre>

for now...

**Comment by ara-oforiwa** [comment]
Hi, 

Having this problem in lb4... I have a property called 'name' of type 'string' which is required... I have no idea why I keep getting internal Error with the message "Cannot read property 'name' of undefined". Any one having this issue in lb4 release? 

Thanks!
